import { PrismaClient, Prisma, ProductStatus } from "../app/generated/prisma";

const prisma = new PrismaClient();

const productData: Prisma.ProductCreateInput[] = [
  {
    name: "Web Development Masterclass",
    description: "Complete guide for modern web development with React, Next.js, and TypeScript.",
    price: 49.99,
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/web-dev-masterclass.pdf",
    category: "E-Books",
    slug: "web-development-masterclass",
    tags: ["webdev", "react", "nextjs", "typescript"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Digital Marketing Blueprint",
    description: "Step-by-step guide for successful digital marketing with templates and tools.",
    price: 29.99,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/digital-marketing-blueprint.pdf",
    category: "E-Books",
    slug: "digital-marketing-blueprint",
    tags: ["marketing", "digital", "strategy", "business"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "UI Component Library",
    description: "200+ professional UI components for Figma and Sketch.",
    price: 39.99,
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/ui-component-library.zip",
    category: "Design Assets",
    slug: "ui-component-library",
    tags: ["ui", "ux", "figma", "sketch", "components"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Icon Pack - 1000+ Icons",
    description: "Comprehensive icon collection in multiple styles with SVG and PNG formats.",
    price: 19.99,
    imageUrl: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/icon-pack-collection.zip",
    category: "Design Assets",
    slug: "icon-pack-collection",
    tags: ["icons", "svg", "png", "design", "ui"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Notion Project Dashboard",
    description: "Professional Notion template for project management with Kanban boards.",
    price: 15.99,
    imageUrl: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/notion-template.zip",
    category: "Templates",
    slug: "notion-project-dashboard",
    tags: ["notion", "template", "project", "management"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Excel Financial Calculator",
    description: "15+ professional Excel templates for financial calculations and planning.",
    price: 24.99,
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/excel-calculator.zip",
    category: "Templates",
    slug: "excel-financial-calculator",
    tags: ["excel", "finance", "calculator", "business"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Business Stock Photos",
    description: "100 high-resolution business stock photos for commercial use.",
    price: 34.99,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/business-photos.zip",
    category: "Stock Media",
    slug: "business-stock-photos",
    tags: ["photos", "stock", "business", "commercial"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Abstract Background Pack",
    description: "50 abstract backgrounds and textures in various colors and styles.",
    price: 16.99,
    imageUrl: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/abstract-backgrounds.zip",
    category: "Stock Media",
    slug: "abstract-background-pack",
    tags: ["graphics", "backgrounds", "abstract", "textures"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "JavaScript Fundamentals Course",
    description: "8-hour video course covering JavaScript basics from variables to async/await.",
    price: 79.99,
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/javascript-course.zip",
    category: "Courses",
    slug: "javascript-fundamentals-course",
    tags: ["javascript", "course", "video", "programming"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Photoshop for Beginners",
    description: "Complete Photoshop course with 6 hours of content and practice files.",
    price: 59.99,
    imageUrl: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/photoshop-course.zip",
    category: "Courses",
    slug: "photoshop-beginners",
    tags: ["photoshop", "design", "course", "beginner"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "Corporate Music Pack",
    description: "20 royalty-free corporate music tracks for videos and presentations.",
    price: 44.99,
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/corporate-music.zip",
    category: "Audio",
    slug: "corporate-music-pack",
    tags: ["music", "royalty-free", "corporate", "audio"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "UI Sound Effects Library",
    description: "150+ UI sound effects for apps and websites including buttons and notifications.",
    price: 21.99,
    imageUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/ui-sounds.zip",
    category: "Audio",
    slug: "ui-sound-effects",
    tags: ["sound", "effects", "ui", "ux", "audio"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "E-commerce Mobile UI Kit",
    description: "Complete UI kit for e-commerce apps with 50+ screens for iOS and Android.",
    price: 69.99,
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/ecommerce-ui-kit.zip",
    category: "Design Assets",
    slug: "ecommerce-mobile-ui-kit",
    tags: ["mobile", "app", "ui", "ecommerce", "figma"],
    status: ProductStatus.PUBLISHED,
  },
  {
    name: "3D Technology Icons",
    description: "80 modern 3D technology icons in multiple formats including OBJ and FBX.",
    price: 32.99,
    imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=300&fit=crop",
    downloadUrl: "https://example-storage.com/downloads/3d-tech-icons.zip",
    category: "Design Assets",
    slug: "3d-technology-icons",
    tags: ["3d", "icons", "technology", "obj", "fbx"],
    status: ProductStatus.PUBLISHED,
  }
]

export async function main(){
    for(const p of productData){
        await prisma.product.create({data: p})
    }
}

main()